// Optional build tooling; the dashboard serves the checked-in bundle.
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cache = resolve(root, process.env.FLYCODEX_WORKSTATION_BUILD_CACHE || 'build/workstation-view-deps');
mkdirSync(cache, {recursive: true});
for (const name of ['package.json', 'package-lock.json']) {
  copyFileSync(resolve(root, 'tools/body-view', name), resolve(cache, name));
}
if (!existsSync(resolve(cache, 'node_modules/esbuild')) || !existsSync(resolve(cache, 'node_modules/three'))) {
  execFileSync('npm', ['ci', '--ignore-scripts', '--no-audit', '--no-fund', '--prefix', cache], {stdio: 'inherit'});
}
const {build} = await import(pathToFileURL(resolve(cache, 'node_modules/esbuild/lib/main.js')));
await build({
  entryPoints: [resolve(root, 'tools/workstation-view/viewer.js')],
  outfile: resolve(root, 'src/flycodex/web/workstation-view.js'),
  bundle: true,
  minify: true,
  format: 'esm',
  target: 'es2022',
  nodePaths: [resolve(cache, 'node_modules')],
  legalComments: 'inline',
  banner: {js: '// Generated by tools/build_workstation_view.mjs. Three.js 0.180.0, MIT; see /body/LICENSE.three.'},
});
