// Optional build tooling; dashboard installations use the checked-in bundle.
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cache = resolve(root, process.env.FLYCODEX_BODY_BUILD_CACHE || 'build/body-view-deps');
mkdirSync(cache, { recursive: true });
for (const name of ['package.json', 'package-lock.json']) {
  copyFileSync(resolve(root, 'tools/body-view', name), resolve(cache, name));
}
execFileSync('npm', ['ci', '--ignore-scripts', '--no-audit', '--no-fund', '--prefix', cache], { stdio: 'inherit' });
const { build } = await import(pathToFileURL(resolve(cache, 'node_modules/esbuild/lib/main.js')));
await build({
  entryPoints: [resolve(root, 'tools/body-view/viewer.js')],
  outfile: resolve(root, 'src/flycodex/web/body-view.js'),
  bundle: true, minify: true, format: 'esm', target: 'es2022',
  nodePaths: [resolve(cache, 'node_modules')], legalComments: 'inline',
  banner: { js: '// Generated by tools/build_body_view.mjs. Three.js 0.180.0, MIT; see /body/LICENSE.three.' },
});
copyFileSync(resolve(cache, 'node_modules/three/LICENSE'), resolve(root, 'src/flycodex/web/body/LICENSE.three'));
writeFileSync(resolve(root, 'src/flycodex/web/body/build.json'), JSON.stringify({ three: '0.180.0', esbuild: '0.25.10' }, null, 2) + '\n');
